#How much mana regen in one second
manaregenunit: 0.5

messageAboutMana: true

#Player data save interval in seconds(Default 10 minute)
saveInterval: 600

#The chance of having the IMP nether star(Default: 5)
netherStarTrade: 5

#The chance of drop brain from mobs(Default: 5%) 0 = off
dropBrainChance: 5

#DataBase settings
#Use DataBase or save all data in individual player file (Default: true)
useDB: true
#Connect to exist database or create and use local db file (Default: true)
localFileDB: true
#Connection settings
host: localhost
port: 3306
dbName: database
user: user
password: password


#Scrolls settings
ARROWSTORM:
  consumedMana: 15.0
  CDseconds: 20
LIGHTNING:
  consumedMana: 5.0 #setting of first type of scroll, other types generate from this setting
  CDseconds: 20 #setting of first type of scroll, other types generate from this setting
NECROMANCY:
  consumedMana: 50.0
  CDseconds: 120
TELEPORTATION:
  consumedMana: 5.0
  CDseconds: 3
VAMPIRIC:
  consumedMana: 6.0
  CDseconds: 6
  damage: 4.0
  regen: 2.0
VORTEX:
  consumedMana: 20.0
  CDseconds: 40
SPIDERWEB:
  perThrowConsumedMana: 1.0
  perThrowCDseconds: 4
  consumedMana: 7.0
  CDseconds: 20
TRAP:
  consumedMana: 17.0
  CDseconds: 30
EARTH:
  consumedMana: 37.0
  CDseconds: 60
ASTRAL_PET:
  consumedMana: 43
  CDseconds: 300
  damage: 7
  secondsLive: 120
METEORITE:
  consumedMana: 43
  CDseconds: 40
SPECTRAL_SHIELD:
  consumedMana: 29
  CDseconds: 300
  seconds: 180
AIR_TRAP:
  consumedMana: 32
  CDseconds: 47
CONFUSED:
  consumedMana: 27
  CDseconds: 34

#Rituals setting
MANAUPFIRST:
  witchesNeed: 0
  state: 80
  needMana: 50
VILLAGER_CAST:
  witchesNeed: 5
  needMana: 35
COOK:
  witchesNeed: 1
  needMana: 20
MANAUPSECOND:
  witchesNeed: 3
  state: 180
  needMana: 80
HEALING:
  witchesNeed: 2
  needMana: 20
DIVER:
  witchesNeed: 2
  needMana: 60
  CDseconds: 1800
MINER:
  witchesNeed: 3
  needMana: 80
  CDseconds: 2400
TRAVELER:
  witchesNeed: 3
  needMana: 90
  CDseconds: 3000
WARRIOR:
  witchesNeed: 4
  needMana: 120
  CDseconds: 3600
IMP_SUMMON:
  witchesNeed: 4
  needMana: 180

#Researches
ANCIENT_BOTTLE:
  neededAspects:
    Experientia: 2200
    Vetustus: 568
    Conruptus: 360
    Alchemiae: 96
    Veneficus: 380
    Cerebrum: 52
MAGIC_SCROLL:
  uses: 160
MANA_SHIELD:
  blockedDamage: 100 #How many times player must block damage
MAGNET:
  handpickedItems: 345 #How many items player must pickup
MAGIC_SCROLL_II:
  neededAspects:
    Veneficus: 350
    Conruptus: 230
    Vetustus: 145
    Instrumentum: 93
    Ridiculum: 18
MANA_SHIELD_II:
  neededAspects:
    Custodia: 768
    Tenebras: 48
    Veneficus: 167
    Tempus: 689
    Mirum: 4
MAGNET_II:
  neededAspects:
    Magneto: 567
    Enucleatus: 246
    Instrumentum: 67
    Captionem: 34
    Tenebras: 2
    Conscientia: 56
    Sanctus: 23


#Mobs
IMP:
  skills:
    MOVE_DODGE:
      time: 20 #seconds
      chance: 15 #in percentages per damage
    ASTRAL_PET_SKILL:
      time: 20
      chance: 30
      damage: 3
    DAMAGE_DODGE:
      chance: 30
      maxDodge: 60 #percentages
  drop:
    chance: 7
  health: 150
  armor: 7

#Other
ManaShield:
  count: #How many times do need to block damage for each mana shield level
    ZERO: 0
    FIRST: 100
    SECOND: 250
    THIRD: 500
    FOURTH: 1000
    FIFTH: 2000
  damage: #How many damage miss the shield'
    ZERO: 0.5
    FIRST: 0.4
    SECOND: 0.35
    THIRD: 0.30
    FOURTH: 0.25
    FIFTH: 0.15
  regen:  #How many mana regen the shield
    ZERO: 0.03
    FIRST: 0.05
    SECOND: 0.07
    THIRD: 0.1
    FOURTH: 0.12
    FIFTH: 0.15
  xplvl: #How many level need to buy
    ZERO: 0
    FIRST: 10
    SECOND: 25
    THIRD: 35
    FOURTH: 50
    FIFTH: 55

lang: 'en_US'