#How much mana regen in one second
manaregenunit: 0.5

messageAboutMana: true

#Scrolls settings
ARROWSTORM:
  consumedMana: 15.0
  CDseconds: 20
LIGHTNING:
  consumedMana: 5.0 #setting of first type of scroll, other types generate from this setting
  CDseconds: 20 #setting of first type of scroll, other types generate from this setting
NECROMANCY:
  consumedMana: 50.0
  CDseconds: 120
TELEPORTATION:
  consumedMana: 5.0
  CDseconds: 3
VAMPIRIC:
  consumedMana: 6.0
  CDseconds: 6
  damage: 4.0
VORTEX:
  consumedMana: 20.0
  CDseconds: 40
SPIDERWEB:
  perThrowConsumedMana: 1.0
  perThrowCDseconds: 4
  consumedMana: 7.0
  CDseconds: 20
TRAP:
  consumedMana: 17.0
  CDseconds: 30
EARTH:
  consumedMana: 37.0
  CDseconds: 60
ASTRAL_PET:
  consumedMana: 43
  CDseconds: 300
  damage: 7
  secondsLive: 120
METEORITE:
  consumedMana: 43
  CDseconds: 40
SPECTRAL_SHIELD:
  consumedMana: 29
  CDseconds: 300
  seconds: 180
AIR_TRAP:
  consumedMana: 32
  CDseconds: 47
CONFUSED:
  consumedMana: 27
  CDseconds: 34

#Rituals setting
MANAUPFIRST:
  witchesNeed: 0
  state: 80
  needMana: 50
VILLAGER_CAST:
  witchesNeed: 5
  needMana: 35
COOK:
  witchesNeed: 1
  needMana: 20
MANAUPSECOND:
  witchesNeed: 3
  state: 180
  needMana: 80
HEALING:
  witchesNeed: 2
  needMana: 20
DIVER:
  witchesNeed: 2
  needMana: 60
  CDseconds: 1800
MINER:
  witchesNeed: 3
  needMana: 80
  CDseconds: 2400
TRAVELER:
  witchesNeed: 3
  needMana: 90
  CDseconds: 3000
WARRIOR:
  witchesNeed: 4
  needMana: 120
  CDseconds: 3600

lang: 'en_US'