name: MagickScrolls
main: ru.vixtor141.MagickScrolls.Main
version: "1.3"
author: vixtor141

softdepend: [PlaceholderAPI]

commands:
  magickscrolls:
    description: base command
    usage: /magickscrolls help
    aliases: ms
permissions:
  magickscrolls.give:
    description: giving a permission on /magickscolls give
  magickscrolls.heal:
    description: giving a permission on /magickscolls heal
  magickscrolls.cdreset:
    description: giving a permission on /magickscolls cdreset
  magickscrolls.give.other:
    description: giving a permission on /magickscolls give other
  magickscrolls.heal.other:
    description: giving a permission on /magickscolls heal other
  magickscrolls.cdreset.other:
    description: giving a permission on /magickscolls cdreset other
  magickscrolls.getinfo:
    description: giving a permission on /magickscolls getinfo
  magickscrolls.give.scroll.ARROWSTORM:
    description: giving a permission on /magickscolls give <nick> ARROWSTORM
  magickscrolls.give.scroll.LIGHTNINGONE:
    description: giving a permission on /magickscolls give <nick> LIGHTNINGONE
  magickscrolls.give.scroll.LIGHTNINGTWO:
    description: giving a permission on /magickscolls give <nick> LIGHTNINGTWO
  magickscrolls.give.scroll.LIGHTNINGTHREE:
    description: giving a permission on /magickscolls give <nick> LIGHTNINGTHREE
  magickscrolls.give.scroll.NECROMANCY:
    description: giving a permission on /magickscolls give <nick> NECROMANCY
  magickscrolls.give.scroll.TELEPORTATION:
    description: giving a permission on /magickscolls give <nick> TELEPORTATION
  magickscrolls.give.scroll.VAMPIRIC:
    description: giving a permission on /magickscolls give <nick> VAMPIRIC
  magickscrolls.give.scroll.VORTEX:
    description: giving a permission on /magickscolls give <nick> VORTEX