name: MagickScrolls
main: ru.vixtor141.MagickScrolls.Main
version: "2.3"
author: vixtor141

softdepend: [PlaceholderAPI]

commands:
  magickscrolls:
    description: base command
    usage: /magickscrolls help
    aliases: ms
permissions:
  magickscrolls.give:
    description: giving a permission on /magickscolls give for scrolls
  magickscrolls.give.artifact:
    description: giving a permission on /magickscolls give for items
  magickscrolls.heal:
    description: giving a permission on /magickscolls heal
  magickscrolls.cdreset:
    description: giving a permission on /magickscolls cdreset
  magickscrolls.give.other:
    description: giving a permission on /magickscolls give other
  magickscrolls.heal.other:
    description: giving a permission on /magickscolls heal other
  magickscrolls.cdreset.other:
    description: giving a permission on /magickscolls cdreset other
  magickscrolls.getinfo:
    description: giving a permission on /magickscolls getinfo
  magickscrolls.list:
    description: giving a permission on /magickscolls list
  magickscrolls.reload:
    description: giving a permission on /magickscolls reload
  magickscrolls.setcurrent:
    description: giving a permission on /magickscolls setcur
  magickscrolls.setmax:
    description: giving a permission on /magickscolls setmax
  magickscrolls.aspect.add:
    description: giving a permission on /magickscolls aspect add
  magickscrolls.aspect.set:
    description: giving a permission on /magickscolls aspect set
  magickscrolls.other.aspect.add:
    description: giving a permission on /magickscolls aspect add for other players
  magickscrolls.other.aspect.set:
    description: giving a permission on /magickscolls aspect set for other players
  magickscrolls.research:
    description: giving a permission on /magickscolls research set
  magickscrolls.research.other:
    description: giving a permission on /magickscolls research set for other players
  magickscrolls.give.scroll.ARROWSTORM:
    description: giving a permission on /magickscolls give <player> ARROWSTORM
  magickscrolls.give.scroll.LIGHTNINGONE:
    description: giving a permission on /magickscolls give <player> LIGHTNINGONE
  magickscrolls.give.scroll.LIGHTNINGTWO:
    description: giving a permission on /magickscolls give <player> LIGHTNINGTWO
  magickscrolls.give.scroll.LIGHTNINGTHREE:
    description: giving a permission on /magickscolls give <player> LIGHTNINGTHREE
  magickscrolls.give.scroll.NECROMANCY:
    description: giving a permission on /magickscolls give <player> NECROMANCY
  magickscrolls.give.scroll.TELEPORTATION:
    description: giving a permission on /magickscolls give <player> TELEPORTATION
  magickscrolls.give.scroll.VAMPIRIC:
    description: giving a permission on /magickscolls give <player> VAMPIRIC
  magickscrolls.give.scroll.VORTEX:
    description: giving a permission on /magickscolls give <player> VORTEX
  magickscrolls.give.scroll.SPIDERWEB:
    description: giving a permission on /magickscolls give <player> SPIDERWEB
  magickscrolls.give.scroll.TRAP:
    description: giving a permission on /magickscolls give <player> TRAP
  magickscrolls.give.scroll.EARTH:
    description: giving a permission on /magickscolls give <player> EARTH
  magickscrolls.give.scroll.ASTRAL_PET:
    description: giving a permission on /magickscolls give <player> ASTRAL PET
  magickscrolls.give.scroll.SPECTRAL_SHIELD:
    description: giving a permission on /magickscolls give <player> SPECTRAL SHIELD
  magickscrolls.give.scroll.AIR_TRAP:
    description: giving a permission on /magickscolls give <player> AIR TRAP
  magickscrolls.give.scroll.CONFUSED:
    description: giving a permission on /magickscolls give <player> CONFUSED