name: MagickScrolls
main: ru.vixtor141.MagickScrolls.Main
version: 1.0
commands:
  magickscrolls:
    description: base command
    usage: /magickscrolls help
    aliases: ms
permissions:
  magickscrolls.give:
    description: giving a permission on /magickscolls give
  magickscrolls.heal:
    description: giving a permission on /magickscolls heal
  magickscrolls.cdreset:
    description: giving a permission on /magickscolls cdreset
  magickscrolls.give.other:
    description: giving a permission on /magickscolls give other
  magickscrolls.heal.other:
    description: giving a permission on /magickscolls heal other
  magickscrolls.cdreset.other:
    description: giving a permission on /magickscolls cdreset other
  magickscrolls.getinfo:
    description: giving a permission on /magickscolls getinfo
  magickscrolls.give.ARROWSTORM:
    description: giving a permission on /magickscolls give <nick> ARROWSTORM
  magickscrolls.give.LIGHTNINGONE:
    description: giving a permission on /magickscolls give <nick> LIGHTNINGONE
  magickscrolls.give.LIGHTNINGTWO:
    description: giving a permission on /magickscolls give <nick> LIGHTNINGTWO
  magickscrolls.give.LIGHTNINGTHREE:
    description: giving a permission on /magickscolls give <nick> LIGHTNINGTHREE
  magickscrolls.give.NECROMANCY:
    description: giving a permission on /magickscolls give <nick> NECROMANCY
  magickscrolls.give.TELEPORTATION:
    description: giving a permission on /magickscolls give <nick> TELEPORTATION
  magickscrolls.give.VAMPIRIC:
    description: giving a permission on /magickscolls give <nick> VAMPIRIC
  magickscrolls.give.VORTEX:
    description: giving a permission on /magickscolls give <nick> VORTEX